/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const Card = (props) => { 
  const { nodes, materials } = useGLTF('/models/card.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.001}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rectangle001_1.geometry}
          material={materials['01 - Default']}
          rotation={[-Math.PI / 2, 0, 0]}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/card.glb')


export default Card;